drop table if exists cat_domain CASCADE;
drop table if exists house_domain CASCADE;
create table cat_domain (id bigint generated by default as identity, age integer not null, name varchar(255) not null, speech_volume float not null, house_id bigint, primary key (id));
create table house_domain (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
alter table cat_domain add constraint FKcwq7yxrqgdpl7syvpsdijpyp4 foreign key (house_id) references house_domain on delete cascade;
